// ignore_for_file: annotate_overrides

import "en.dart";

class Ar implements En {
  Direction $direction = Direction.rtl;
  String $name = "العربية";
  String $code = "ar";

  Map<String, String> dictionary ={
    "cancel": "إلغاء",
    "close": "إغلاق",
    "save": "حفظ",
    "reset": "إعادة تعيين",
    "continue": "استمرار",
    "add": "إضافة",
    "edit": "تعديل",
    "delete": "حذف",
    "archive": "أرشفة",
    "restore": "استعادة",
    "logout": "تسجيل الخروج",
    "noResultsFound": "لم يتم العثور على نتائج",
    "home": "الرئيسية",
    "calendar": "التقويم",
    "gettingImages": "جاري جلب الصور",

    // call
    "callLaboratory": "الاتصال بالمختبر",
    "callPatient": "الاتصال بالمريض",
    "emailDoctor": "إرسال بريد للطبيب",
    "callIssuer": "الاتصال بالمصدر",

    // screens
    "settings": "الإعدادات",
    "dashboard": "لوحة التحكم",
    "appointments": "المواعيد",
    "patients": "المرضى",
    "doctors": "الأطباء",
    "labworks": "الأعمال المخبرية",
    "statistics": "الإحصائيات",

    // dashboard
    "admin": "مشرف",
    "fullStats": "إحصائيات كاملة",
    "payments": "المدفوعات",
    "appointmentsToday": "مواعيد اليوم",
    "patientsToday": "المرضى اليوم",
    "newPatientsToday": "المرضى الجدد اليوم",
    "paymentsMadeToday": "المدفوعات المنجزة اليوم",
    "modeAdmin": "مشرف",
    "modeUser": "مستخدم",
    "modeOffline": "غير متصل",
    "onceConnectionIsStable": "عند استقرار الاتصال يمكنك استخدام الزر في الزاوية العليا اليمنى لإعادة الاتصال.",
    "unRestrictedAccess": "وصول غير مقيد في التطبيق",
    "restrictedAccess": "وصول مقيد لبعض الشاشات كما يحدده المسؤول",
    "youAreCurrentlyIn": "أنت حالياً في وضع",
    "mode": "الوضع",
    "youHave": "لديك",
    "hello": "مرحباً",

    // datatable
    "archiveSelected": "أرشفة المحدد",
    "searchPlaceholder": "بحث...",
    "showHideArchived": "إظهار/إخفاء المؤرشف",
    "showing": "عرض",
    "by": "بواسطة",
    "byTitle": "حسب العنوان",
    "byDate": "حسب التاريخ",
    "noItemsFound": "لم يتم العثور على عناصر",
    "filter": "تصفية",

    // doctors
    "doctor": "طبيب",
    "newDoctor": "طبيب جديد",
    "doctorDetails": "تفاصيل الطبيب",
    "pastAppointments": "المواعيد السابقة",
    "upcomingAppointments": "المواعيد القادمة",
    "doctorName": "اسم الطبيب",
    "doctorEmail": "بريد الطبيب الإلكتروني",
    "dutyDays": "أيام الدوام",
    "addAppointment": "إضافة موعد",
    "lockToUsers": "فقط المستخدمون التاليون يمكنهم عرض/تعديل بيانات ومواعيد هذا الطبيب",
    "noUpcomingAppointmentsForThisDoctor": "لا توجد مواعيد قادمة. استخدم الزر بالأسفل لتسجيل موعد جديد.",

    // days and months
    "monday": "الإثنين",
    "tuesday": "الثلاثاء",
    "wednesday": "الأربعاء",
    "thursday": "الخميس",
    "friday": "الجمعة",
    "saturday": "السبت",
    "sunday": "الأحد",
    "january": "يناير",
    "february": "فبراير",
    "march": "مارس",
    "april": "أبريل",
    "may": "مايو",
    "june": "يونيو",
    "july": "يوليو",
    "august": "أغسطس",
    "september": "سبتمبر",
    "october": "أكتوبر",
    "november": "نوفمبر",
    "december": "ديسمبر",

    // appointment card
    "appointment": "موعد",
    "Patient": "مريض",
    "photos": "صور",
    "pre-opNotes": "ملاحظات قبل العملية",
    "post-opNotes": "ملاحظات بعد العملية",
    "prescription": "وصفة طبية",
    "pay": "دفع",
    "Paid": "مدفوع",
    "price": "السعر",
    "underpaid": "مدفوع جزئياً",
    "overpaid": "مدفوع أكثر من اللازم",
    "fullyPaid": "مدفوع بالكامل",
    "paymentSummary": "ملخص الدفع",
    "editingAppointment": "تعديل الموعد",
    "after": "بعد",
    "days": "أيام",
    "day": "يوم",
    "isDone": "تم إجراء الموعد",

    // patients
    "patientDetails": "تفاصيل المريض",
    "Age": "العمر",
    "Gender": "الجنس",
    "Last visit": "آخر زيارة",
    "Total payments": "إجمالي المدفوعات",
    "daysAgo": "قبل أيام",
    "noVisits": "لا توجد زيارات",
    "addNewPatient": "إضافة مريض جديد",
    "name": "الاسم",
    "birthYear": "سنة الميلاد",
    "phone": "الهاتف",
    "email": "البريد الإلكتروني",
    "address": "العنوان",
    "notes": "ملاحظات",
    "patientTags": "وسوم المريض",
    "male": "ذكر",
    "female": "أنثى",
    "noAppointmentsFound": "لم يتم العثور على مواعيد لهذا المريض، استخدم الزر بالأسفل لإضافة موعد جديد.",
    "editPatient": "تعديل المريض",
    "editAppointment": "تعديل الموعد",
    "patientPage": "صفحة المريض",
    "patientCanUseTheFollowing": "يمكن للمريض استخدام الرابط التالي للوصول إلى مواعيده ومدفوعاته وصوره.",
    "printQR": "طباعة رمز QR",
    "dentalNotes": "ملاحظات الأسنان",
    "showPrimary": "عرض الأسنان اللبنية",
    "showPermanent": "عرض الأسنان الدائمة",
    "primary": "لبني",
    "permanent": "دائم",
    "lower": "سفلي",
    "upper": "علوي",
    "left": "يسار",
    "right": "يمين",
    "centralIncisor": "قاطع مركزي",
    "lateralIncisor": "قاطع جانبي",
    "canine": "ناب",
    "firstPremolar": "ضاحك أول",
    "secondPremolar": "ضاحك ثاني",
    "firstMolar": "طاحن أول",
    "secondMolar": "طاحن ثاني",
    "thirdMolar": "ضرس العقل",
    "exportSelected": "تصدير المحدد",
    "noPatientsSelected": "لم يتم تحديد مرضى",

    // calendar (appointments)
    "allDoctors": "جميع الأطباء",
    "noAppointmentsForThisDay": "لا توجد مواعيد في هذا اليوم",
    "weekAbbr": "أ",
    "twoWeeksAbbr": "2أ",
    "monthAbbr": "ش",
    "today": "اليوم",
    "newPatient": "مريض جديد",
    "date": "التاريخ",
    "changeDate": "تغيير التاريخ",
    "changeTime": "تغيير الوقت",
    "attention": "انتباه",
    "doctorNotAvailable": "قد لا يكون أحد الأطباء متاحاً في التاريخ المحدد.",
    "time": "الوقت",
    "preOperativeNotes": "ملاحظات قبل العملية",
    "selectDoctors": "اختر الأطباء",
    "selectPatient": "اختر المريض",
    "operativeDetails": "تفاصيل العملية",
    "postOperativeNotes": "ملاحظات بعد العملية",
    "printPrescription": "طباعة الوصفة",
    "priceIn": "السعر بـ",
    "paidIn": "مدفوع بـ",
    "gallery": "معرض الصور",
    "link": "الرابط",
    "upload": "رفع",
    "camera": "الكاميرا",
    "emptyGallery": "المعرض فارغ",
    "noPhotos": "لم يتم تحميل أي صور بعد.",
    "importingPhotosFromLink": "استيراد صور من رابط",
    "useThisForm": "استخدم هذا النموذج لاستيراد الصور من روابط مشاركة مثل صور Google أو صفحات ويب تحتوي على صور تريد إضافتها لهذا الموعد.",
    "error": "خطأ",
    "enterLink": "أدخل رابط يحتوي على صور",
    "import": "استيراد",

    // labworks
    "Laboratory": "المختبر",
    "Month": "شهر",
    "newLabwork": "عمل مخبري جديد",
    "labwork": "عمل مخبري",
    "labworkTitle": "عنوان العمل المخبري",
    "orderNotes": "ملاحظات الطلب",
    "unpaid": "غير مدفوع",
    "noSuggestions": "لا توجد اقتراحات",

    // expenses
    "expense": "مصروف",
    "expenses": "المصاريف",
    "receipt": "إيصال",
    "title": "العنوان",
    "cost": "التكلفة",
    "issuer": "المصدر",
    "amount": "المبلغ",
    "amountIn": "المبلغ بـ",
    "status": "الحالة",
    "due": "مستحق",
    "receiptTitle": "عنوان الإيصال",
    "receiptNotes": "ملاحظات الإيصال",
    "newReceipt": "إيصال جديد",
    "receiptTags": "وسوم الإيصال",
    "receiptItems": "بنود الإيصال",
    "specificForDoctors": "مخصص للأطباء التاليين",

    // stats
    "pickRange": "اختر المدى",
    "start": "البداية",
    "end": "النهاية",
    "weeks": "أسابيع",
    "months": "أشهر",
    "quarters": "أرباع",
    "years": "سنوات",
    "appointmentsPer": "مواعيد حسب",
    "paymentsAndExpensesPer": "المدفوعات والمصاريف حسب",
    "newPatientsPer": "المرضى الجدد حسب",
    "doneMissedPer": "المنجزة والمفقودة حسب",
    "timeOfDay": "الوقت من اليوم",
    "dayOfWeek": "يوم الأسبوع",
    "dayOfMonth": "يوم من الشهر",
    "monthOfYear": "شهر من السنة",
    "patientsGender": "جنس المرضى",
    "total": "المجموع",
    "in_Duration_": "خلال",
    "acquiredPatientsIn": "المرضى المكتسبون في",
    "doneAndMissedAppointmentsIn": "المواعيد المنجزة والمفقودة في",
    "distributionOfAppointments": "توزيع المواعيد",
    "maleAndFemalePatients": "المرضى الذكور والإناث",
    "done": "منجز",
    "missed": "مفقود",

    // settings
    "currency": "العملة",
    "currency_desc": "رمز العملة المستخدم في التطبيق (مثل USD، EUR، IQD).",
    "phone_desc": "سيتم عرض رقم الهاتف في الطباعة وصفحة المريض.",
    "prescriptionFooter": "تذييل الوصفة",
    "prescriptionFooter_desc": "سيتم عرض هذا النص أسفل الوصفة الطبية.",
    "language": "اللغة",
    "language_desc": "لغة الواجهة والقوائم والأزرار المستخدمة في التطبيق.",
    "startingDayOfWeek": "بداية الأسبوع",
    "startingDayOfWeek_desc": "اليوم الذي يبدأ فيه الأسبوع.",
    "dateFormat": "تنسيق التاريخ",
    "dateFormat_desc": "سيتم استخدام هذا التنسيق لعرض التواريخ حيثما كان ذلك مناسباً.",
    "cacheReset": "إعادة تعيين الذاكرة المؤقتة",
    "cacheReset_desc": "يمكنك حذف البيانات المخزنة محليًا (باستثناء الصور) لحل مشاكل التزامن المحتملة.",
    "month/day/year": "شهر/يوم/سنة",
    "day/month/year": "يوم/شهر/سنة",
    "appliesTo": "ينطبق على",
    "all": "الكل",
    "you": "أنت",
    "initialSynchronization": "المزامنة الأولية",
    "synchronizing": "جارٍ المزامنة",
    "clearingLocalData": "جاري مسح البيانات المحلية",

    // advanced settings: Backups
    "backups": "النسخ الاحتياطية",
    "refresh": "تحديث",
    "download": "تنزيل",
    "createNew": "إنشاء جديد",
    "restoreBackup": "استعادة النسخة الاحتياطية",
    "restoreBackupWarning1": "استعادة هذه النسخة ستقوم بالكتابة فوق جميع البيانات الحالية في التطبيق. أي تغييرات قمت بها بعد تاريخ هذه النسخة",
    "restoreBackupWarning2": "سيتم فقدانها.\n\nهل أنت متأكد أنك تريد استعادة هذه النسخة؟",
    "sureDeleteBackup": "هل أنت متأكد أنك تريد حذف هذه النسخة الاحتياطية؟",
    "backupDate": "تاريخ النسخة الاحتياطية",
    "useTheFollowingLinkToDownloadTheBackup": "استخدم الرابط التالي لتنزيل النسخة الاحتياطية",

    // advanced settings: Admins
    "admins": "المشرفون",
    "accountCreated": "تم إنشاء الحساب",
    "editAdmin": "تعديل المشرف",
    "validEmailMustBeProvided": "يجب توفير بريد إلكتروني صالح",
    "password": "كلمة المرور",
    "leaveBlankToKeepUnchanged": "اتركه فارغاً إذا لم ترغب في التغيير",
    "updatingPassword": "تحديث كلمة المرور",
    "leaveItEmpty": "اترك حقل كلمة المرور فارغًا إذا لم تكن تريد تغييره.",
    "newAdmin": "مشرف جديد",
    "minimumPasswordLength": "كلمة المرور يجب أن تتكون من 10 أحرف على الأقل",

    // advanced settings: Users
    "users": "المستخدمون",
    "editUser": "تعديل المستخدم",
    "newUser": "مستخدم جديد",

    // advanced settings: Permissions
    "permissions": "صلاحيات المستخدم",
    "usersCanAccess": "يمكن للمستخدمين الوصول إلى",
    "permissionsNotice": "تنطبق الصلاحيات التالية على المستخدمين المحددين وأثناء العمل دون اتصال. ومع ذلك، لدى المشرفين وصول غير مقيد في التطبيق، ما لم يكونوا غير متصلين.",

    // advanced settings: prod tests
    "prodTests": "اختبارات الإنتاج",
    "fileStorageTest": "اختبار تخزين الملفات",
    "fileStorageTestDesc": "استخدم الزر التالي لاختبار ما إذا كانت إعدادات التخزين S3 تعمل بشكل صحيح.",
    "fileStorageButton": "اختبار إعداد S3",
    "fileStorageFail": "فشل إعداد S3",
    "fileStorageSuccess": "إعداد S3 يعمل بشكل صحيح",
    "emailTest": "اختبار البريد الإلكتروني",
    "emailTestDesc": "استخدم الزر التالي لاختبار ما إذا كان بإمكان الخادم إرسال رسائل البريد الإلكتروني. سيتم إرسال رسالة مماثلة لإعادة تعيين كلمة المرور إلى العنوان المحدد.",
    "targetEmail": "البريد الإلكتروني الهدف",
    "emailTestButton": "إرسال رسالة اختبار",
    "emailTestFail": "فشل اختبار البريد الإلكتروني",
    "emailTestSuccess": "تم إرسال البريد الإلكتروني بنجاح، يرجى التحقق من صندوق الوارد الخاص بك.",
    "fail": "فشل",
    "success": "نجاح",

    // login
    "login": "تسجيل الدخول",
    "resetPassword": "إعادة تعيين كلمة المرور",
    "serverUrl": "رابط الخادم",
    "proceedOffline": "المتابعة بدون اتصال",
    "youLLGet": "سيتم إرسال رابط إعادة التعيين عبر البريد الإلكتروني",
    "beenSent": "تم إرسال تعليمات إعادة تعيين كلمة المرور إليك، تحقق من بريدك الوارد.",

    // other
    "sureArchiveSelected": "هل أنت متأكد أنك تريد أرشفة العناصر المحددة؟",
    "sureClosePanel": "هل أنت متأكد أنك تريد إغلاق هذه اللوحة؟ أي تغييرات غير محفوظة ستضيع.",
    "sure": "متأكد",
    "back": "رجوع",
    "firstLaunchDialogTitle": "مرحبًا بك في Apexo",
    "firstLaunchDialogContent": "لقد قمت بتثبيت Apexo بنجاح. ومع ذلك، لتحسين التجربة وللاستخدام العملي، ستحتاج إلى إعداد بعض الأمور. امسح رمز QR أدناه للبدء.",
    "newVersionDialogTitle": "نسخة جديدة متاحة",
    "newVersionDialogContent": "نسخة جديدة من Apexo متاحة. يرجى التحديث إلى آخر إصدار للحصول على أفضل تجربة. امسح رمز QR أدناه للبدء.",
  "phoneValidation" : "يرحى ادخال رقم هاتف صحيح ",
    "emailvalidation" : "يرحى ادخال ايميل صحيح",
    "birtv" : "يرحى ادخال ميلاد صحيح"



  };

}
